// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRp4mhrd4rZ_ebkoqPlpSeL1_GDH7yIU',
    appId: '1:477856452577:web:734d64d14a8781e0a30ca0',
    messagingSenderId: '477856452577',
    projectId: 'fir-flutter-codelab-da8c9',
    authDomain: 'fir-flutter-codelab-da8c9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-da8c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuq-XlHk0X4NsJm3-VKk4zsyGE2DklZco',
    appId: '1:477856452577:android:908f78b68de3f668a30ca0',
    messagingSenderId: '477856452577',
    projectId: 'fir-flutter-codelab-da8c9',
    storageBucket: 'fir-flutter-codelab-da8c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC1M0vMXQdTOCqXqGOEn9GP71U7H8n6iM',
    appId: '1:477856452577:ios:b32d49f8b69a61d3a30ca0',
    messagingSenderId: '477856452577',
    projectId: 'fir-flutter-codelab-da8c9',
    storageBucket: 'fir-flutter-codelab-da8c9.appspot.com',
    iosClientId: '477856452577-v1dveo8h7hkekm410a5cdceu7j5g4lhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC1M0vMXQdTOCqXqGOEn9GP71U7H8n6iM',
    appId: '1:477856452577:ios:b32d49f8b69a61d3a30ca0',
    messagingSenderId: '477856452577',
    projectId: 'fir-flutter-codelab-da8c9',
    storageBucket: 'fir-flutter-codelab-da8c9.appspot.com',
    iosClientId: '477856452577-v1dveo8h7hkekm410a5cdceu7j5g4lhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
